commerce_license.commerce_license_type.*:
  type: config_entity
  label: 'License type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    variationType:
      type: string
      label: 'Variation type'
    injectVariationFields:
      type: boolean
      label: 'Inject license variation fields into the rendered license'

commerce_license.commerce_license_variation_type.*:
  type: config_entity
  label: 'License variation type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    orderItemType:
      type: string
      label: 'order item type'
    generateTitle:
      type: boolean
      label: 'Generate variation titles based on attribute values'

commerce_license.commerce_license_attribute.*:
  type: config_entity
  label: 'License attribute'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    elementType:
      type: string
      label: 'Element type'

field.formatter.settings.commerce_add_to_cart:
  type: mapping
  mapping:
    show_quantity:
      type: boolean
      label: 'Whether to display a quantity input field on the add to cart form.'
    default_quantity:
      type: string
      label: 'Default quantity'
    combine:
      type: boolean
      label: 'Whether to attempt to combine order items containing the same license variation'

field.formatter.settings.commerce_license_attributes_overview:
  type: mapping
  mapping:
    attributes:
      type: sequence
      label: 'Attributes to render.'
      sequence:
        type: string
        label: 'Attribute ID'
    view_mode:
      type: string
      label: 'View mode'

field.widget.settings.commerce_license_variation_title:
  type: mapping
  label: 'License variation title widget settings'
  mapping:
    label_display:
      type: boolean
      label: 'Label display'
    label_text:
      type: label
      label: 'Label text'

action.configuration.commerce_publish_license:
  type: action_configuration_default
  label: 'Configuration for the Publish license action'

action.configuration.commerce_unpublish_license:
  type: action_configuration_default
  label: 'Configuration for the Unpublish license action'
